#!/bin/bash

set -e

# This release script assumes that you have AmazeeIO/homebrew-cachalot checked
# out as a sibling to this checkout.

VERSION=$1
TODAY=$(date "+%Y-%m-%d")

: ${VERSION:?"Need to specify a version e.g. 2.0.1"}

sed -i '' "s/CACHALOT_VERSION=.*/CACHALOT_VERSION='$VERSION'/g" cli/amazeeio_cachalot/version.rb
sed -i '' $'s/## Unreleased/## Unreleased\
\
## '"$VERSION - $TODAY/g" CHANGELOG.md

git commit -am "v$VERSION"
git tag "v$VERSION"
REF=$(git show-ref -s "v$VERSION")
git push origin "v$VERSION"
git push origin master:master

pushd ../homebrew-cachalot
sed -i '' 's|  url ".*|  url "https://github.com/AmazeeIO/cachalot.git", :tag => "v'$VERSION'", :revision => "'$REF'"|' Formula/amazeeio_cachalot.rb
git commit -am "release v$VERSION"
git push origin master:master
popd
