require 'tempfile'

require 'amazeeio_cachalot/daemon'

class Dnsmasq
  include AmazeeIOCachalot::Daemon
  RESOLVER_DIR = Pathname("/etc/resolver")

  attr_reader :ip, :resolver_file, :amazeeio_cachalot_domain

  def initialize(ip, amazeeio_cachalot_domain)
    @ip = ip
    self.amazeeio_cachalot_domain = amazeeio_cachalot_domain || "docker.amazee.io"
  end

  def amazeeio_cachalot_domain=(amazeeio_cachalot_domain)
    @amazeeio_cachalot_domain = amazeeio_cachalot_domain
    @resolver_file = RESOLVER_DIR.join(@amazeeio_cachalot_domain)
  end

  def up
    unless resolver_configured?
      configure_resolver!
    end
    super
  end

  def name
    "DNS"
  end

  def configure_resolver!
    puts "setting up DNS resolution, this will require sudo"
    unless RESOLVER_DIR.directory?
      system!("creating #{RESOLVER_DIR}", "sudo", "mkdir", "-p", RESOLVER_DIR)
    end
    Tempfile.open('amazeeio_cachalot-dnsmasq') do |f|
      f.write(resolver_contents)
      f.close
      system!("creating #{@resolver_file}", "sudo", "cp", f.path, @resolver_file)
      system!("creating #{@resolver_file}", "sudo", "chmod", "644", @resolver_file)
    end
    system!("restarting mDNSResponder", "sudo", "killall", "mDNSResponder")
  end

  def resolver_configured?
    @resolver_file.exist? && File.read(@resolver_file) == resolver_contents
  end

  def resolver_contents; <<-EOS.gsub(/^    /, '')
    # Generated by amazeeio_cachalot
    nameserver 127.0.0.1
    port 19323
    EOS
  end

  protected

  def command
    [
      "#{AmazeeIOCachalot.brew}/sbin/dnsmasq",
      "--no-daemon",
      "--listen-address=127.0.0.1",
      "--port=19323",
      "--bind-interfaces",
      "--no-resolv",
      "--address=/.#{amazeeio_cachalot_domain}/#{ip}"
    ]
  end
end
